version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .  
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./input:/opt/airflow/input
    - ./output:/opt/airflow/output
  networks:
    - code-with-yu

services:
  webserver:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow webserver"
    ports:
      - "8080:8080"
    restart: always
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'

  scheduler:
    <<: *airflow-common
    command: bash -c "
      airflow db upgrade &&
      airflow users create \
        --username admin \
        --firstname Hajar \
        --lastname Halmaoui \
        --role Admin \
        --email hajarhalmaoui.1@gmail.com \
        --password admin || echo 'Admin user already exists' &&
      airflow scheduler"
    restart: always
    depends_on:
      - webserver
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - code-with-yu
    ports:
      - "5432:5432"

  selenium:
    image: selenium/standalone-chrome:latest  # Use the correct image name
    ports:
      - "4444:4444"
    networks:
      - code-with-yu
networks:
  code-with-yu:

volumes:
  postgres_data:
